In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("titanic.csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
cols = ['Sex','Survived','Pclass']

In [5]:
df_new= df[cols]

In [6]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
Sex         891 non-null object
Survived    891 non-null int64
Pclass      891 non-null int64
dtypes: int64(2), object(1)
memory usage: 21.0+ KB


In [7]:
df_new.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [8]:
df_new.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [9]:
df_new.head()

Sex  Survived  Pclass
0    male         0       3
1  female         1       1
2  female         1       3
3  female         1       1
4    male         0       3

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_new = df_new.apply(le.fit_transform)   # 1 for male and 0 for female # 0 for not survived # 1 for survived

In [11]:
# create contingency table
table = pd.crosstab(df['Sex'],df['Survived'])

In [12]:
table2 = pd.crosstab(df['Pclass'],df['Survived'])

In [13]:
table2

Survived    0    1
Pclass            
1          80  136
2          97   87
3         372  119

In [14]:
table

Survived    0    1
Sex               
female     81  233
male      468  109

In [15]:
import scipy.stats
result = scipy.stats.chi2_contingency(table)
result

(260.71702016732104,
 1.1973570627755645e-58,
 1,
 array([[193.47474747, 120.52525253],
        [355.52525253, 221.47474747]]))

In [16]:
import scipy.stats
result_pclass = scipy.stats.chi2_contingency(table2)
result_pclass

(102.88898875696056,
 4.549251711298793e-23,
 2,
 array([[133.09090909,  82.90909091],
        [113.37373737,  70.62626263],
        [302.53535354, 188.46464646]]))

In [17]:
expected_freq = result[3]
degree_of_freedom = result[2]
p_value = result[1]
chi_static = result[0]


In [18]:
expected_freq_pclass = result_pclass[3]
degree_of_freedom_pclass = result_pclass[2]
p_value_pclass = result_pclass[1]
chi_static_pclass = result_pclass[0]


In [19]:
observed_freq = table.values
observed_freq_pclass = table2.values

In [20]:
from scipy.stats import chi2
alpha=0.05
#critical_value
critical_value=chi2.ppf(q=1-alpha,df=degree_of_freedom)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [21]:
from scipy.stats import chi2
alpha=0.05
#critical_value
critical_value_pclass=chi2.ppf(q=1-alpha,df=degree_of_freedom_pclass)
print('critical_value:',critical_value_pclass)

critical_value: 5.991464547107979


In [22]:
if chi_static >=critical_value: 
    print("we can reject null hypothesis. Relationship exists between these 2 categories")
else:
    print("no relaionship")

we can reject null hypothesis. Relationship exists between these 2 categories


In [23]:
if chi_static_pclass >=critical_value_pclass: 
    print("we can reject null hypothesis. Relationship exists between these 2 categories")
else:
    print("no relaionship")

we can reject null hypothesis. Relationship exists between these 2 categories
